apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awssecrets.mumoshu.github.io
spec:
  group: mumoshu.github.io
  names:
    kind: AWSSecret
    listKind: AWSSecretList
    plural: awssecrets
    singular: awssecret
  scope: ""
  validation:
    openAPIV3Schema:
      description: AWSSecret is the Schema for the awssecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AWSSecretSpec defines the desired state of AWSSecret
          properties:
            stringDataFrom:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file'
              properties:
                secretsManagerSecretRef:
                  description: SecretsManagerSecretRef defines from which SecretsManager
                    Secret the Kubernetes secret is built See https://docs.aws.amazon.com/secretsmanager/latest/userguide/terms-concepts.html
                    for the concepts
                  properties:
                    secretId:
                      description: SecretId is the SecretId a.k.a `--secret-id` of
                        the SecretsManager secret version
                      type: string
                    versionId:
                      description: VersionIdis the VersionId a.k.a `--version-id`
                        of the SecretsManager secret version
                      type: string
                  type: object
              type: object
          type: object
        status:
          description: AWSSecretStatus defines the observed state of AWSSecret
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
